spring:
  profiles:
    active: dev
server:
  port: 3100
  session:
    timeout: 7200
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 16384
debug: false
mybatis:
  type-aliases-package: com.smip.entity

